### ISSUE TITLE
Qiitaデザイン変更後、複製ボタンに不具合が起きました

### ISSUE THREAD

**Issue by tatsuyatatsuya** [fukayatsu/duplicate-for-qiita-crx#5]
下記の現象が、3月後半のQiitaデザイン変更後、起きるようになりました。

1. 複製ボタンが二つ見えるようになりました
![2015-04-03 16 28 33](https://cloud.githubusercontent.com/assets/6329239/6979471/11f6a8c4-da1f-11e4-8a0d-f11881e4c41e.png)

2. 右側の複製ボタンは恐ろしい状態になっています
![2015-04-03 16 28 28](https://cloud.githubusercontent.com/assets/6329239/6979475/2078d2e6-da1f-11e4-95bc-17aceafd4422.png)

3. どちらの複製ボタンを押してもタグが複製できなくなりました

4. お元気ですかｗ？

**Comment by fukayatsu** [comment]
わろたｗ

後ほど修正します〜 (元気です

**Comment by fukayatsu** [comment]
storeにVersion: 0.0.4をpublishしたので1時間ぐらいで配布されると思います〜

**Comment by tatsuyatatsuya** [comment]
遅れました！素晴らしく直ってます、ありがとうございます٩(ˊᗜˋ*)و

**Comment by fukayatsu** [comment]
٩(๑❛ᴗ❛๑)۶
